INSERT INTO crop_calendar (
  crop_name_en,
  crop_name_bn,
  division,
  sow_months,
  harvest_months,
  avg_yield,
  notes_en,
  notes_bn,
  image_url
) VALUES

-- ── GRAINS ──────────────────────────────────────────────────

('Aman Rice',
 'আমন ধান',
 NULL,
 ARRAY[7, 8],
 ARRAY[11, 12],
 '2.5–4.5 ton/hectare',
 'Main monsoon rain-fed paddy of Bangladesh. Planted in kharif season, harvested in late autumn. Widely grown across all divisions.',
 'বাংলাদেশের প্রধান বর্ষাকালীন ধান। খরিফ মৌসুমে রোপণ করা হয় এবং হেমন্তে কাটা হয়।',
 'https://www.amanbrand.in/cdn/shop/files/1121.jpg?v=1714771320&width=1445'),

('Boro Rice',
 'বোরো ধান',
 NULL,
 ARRAY[1, 2],
 ARRAY[4, 5],
 '4.5–7.0 ton/hectare',
 'Highest yielding irrigated dry-season rice. Requires controlled irrigation. Grown January to May across most divisions.',
 'সর্বোচ্চ উৎপাদনশীল সেচনির্ভর শুষ্ক মৌসুমের ধান। নিয়ন্ত্রিত সেচ প্রয়োজন।',
 'https://www.tbsnews.net/sites/default/files/styles/big_3/public/images/2022/11/09/rice.jpg'),

('Aus Rice',
 'আউশ ধান',
 NULL,
 ARRAY[3, 4],
 ARRAY[7, 8],
 '1.5–2.5 ton/hectare',
 'Early season rice sown before the monsoon. Short duration variety, mainly grown in Sylhet and Chittagong divisions.',
 'বর্ষার আগে বোনা আগাম মৌসুমের ধান। স্বল্পমেয়াদী জাত।',
 'https://lh4.googleusercontent.com/proxy/8Eo8n44dQ807voJqej-CmrTGXkRjlGvVrjp1WEXJQHO2l1qbhxbfTTe1VYKuqz0IYXyzCJHv4Dm7_S8_y4oHzoEme1zdEWBKxP2vbeTy7NnXlQ'),

('Wheat',
 'গম',
 NULL,
 ARRAY[11, 12],
 ARRAY[3, 4],
 '2.0–3.5 ton/hectare',
 'Winter crop grown in northern and central Bangladesh. Needs cool temperature below 20°C for best yield. Rajshahi and Rangpur divisions are main producers.',
 'শীতকালীন ফসল, উত্তর ও মধ্যবাংলাদেশে চাষ হয়। সর্বোচ্চ ফলনের জন্য ২০ ডিগ্রির নিচে তাপমাত্রা দরকার।',
 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRzRai9wwC9hKIAsVtdADxf8uK42SJjwVzMCw&s'),

('Maize',
 'ভুট্টা',
 NULL,
 ARRAY[10, 11],
 ARRAY[2, 3],
 '6.0–9.0 ton/hectare',
 'High-yielding winter crop gaining popularity in Rangpur, Rajshahi, and Dinajpur. Used as animal feed and food.',
 'উচ্চ ফলনশীল শীতকালীন ফসল। রংপুর, রাজশাহী ও দিনাজপুরে জনপ্রিয়।',
 ''),

('Jute',
 'পাট',
 NULL,
 ARRAY[3, 4, 5],
 ARRAY[7, 8],
 '2.0–3.5 ton/hectare (dry fiber)',
 'Golden fiber of Bangladesh. Grown in warm humid conditions. Faridpur, Mymensingh, and Dhaka divisions are main producers.',
 'বাংলাদেশের সোনালী আঁশ। উষ্ণ আর্দ্র আবহাওয়ায় জন্মে। ফরিদপুর, ময়মনসিংহ ও ঢাকা বিভাগ প্রধান উৎপাদন এলাকা।',
 'https://www.keshrinandan.com/wp-content/uploads/2015/08/ke_maize_nutrition.jpg'),

('Sugarcane',
 'আখ',
 NULL,
 ARRAY[1, 2, 3],
 ARRAY[11, 12, 1],
 '40–60 ton/hectare (cane weight)',
 'Long-duration crop taking 10 to 12 months. Rajshahi, Rangpur, and Kushtia are main growing areas. Used for sugar and molasses production.',
 'দীর্ঘমেয়াদী ফসল, ১০–১২ মাস লাগে। রাজশাহী, রংপুর ও কুষ্টিয়া প্রধান এলাকা।',
 ''),

-- ── VEGETABLES ──────────────────────────────────────────────

('Potato',
 'আলু',
 NULL,
 ARRAY[10, 11],
 ARRAY[1, 2, 3],
 '20–30 ton/hectare',
 'Most important winter vegetable. Munshiganj, Comilla, and Rangpur are largest producing districts. Requires well-drained loamy soil.',
 'সবচেয়ে গুরুত্বপূরণ শীতকালীন সবজি। মুন্সীগঞ্জ, কুমিল্লা ও রংপুর প্রধান উৎপাদনকারী জেলা।',
 'https://www.simplotfood.com/_next/image?url=https%3A%2F%2Fimages.ctfassets.net%2F0dkgxhks0leg%2FRKiZ605RAV8kjDQnxFCWP%2Fb03b8729817c90b29b88d536bfd37ac5%2F9-Unusual-Uses-For-Potatoes.jpg%3Ffm%3Dwebp&w=1920&q=75'),

('Tomato',
 'টমেটো',
 NULL,
 ARRAY[10, 11],
 ARRAY[1, 2, 3],
 '15–25 ton/hectare',
 'Winter vegetable crop. Requires cool temperature and well-drained fertile soil. Widely grown in Jessore, Comilla, and Rajshahi.',
 'শীতকালীন সবজি। ঠান্ডা আবহাওয়া ও সুনিষ্কাশিত উর্বর মাটি প্রয়োজন।',
 'https://www.richardjacksonsgarden.co.uk/wp-content/uploads/2021/04/AdobeStock_554658202_1200px.jpg'),

('Cauliflower',
 'ফুলকপি',
 NULL,
 ARRAY[9, 10],
 ARRAY[12, 1, 2],
 '15–20 ton/hectare',
 'Popular cool season vegetable. Seedlings transplanted in October. Ready to harvest in 60 to 90 days after transplanting.',
 'জনপ্রিয় শীতকালীন সবজি। অক্টোবরে চারা রোপণ করা হয়। রোপণের ৬০–৯০ দিন পর কাটা যায়।',
 'https://cdn.britannica.com/24/140624-050-A8237BB9/Cauliflower-plant-form-cauliflower-cabbage-flower-structures.jpg'),

('Cabbage',
 'বাঁধাকপি',
 NULL,
 ARRAY[9, 10],
 ARRAY[12, 1, 2],
 '20–30 ton/hectare',
 'Cool season crop similar to cauliflower. Grown across all divisions in winter. Prefers loamy soil with good drainage.',
 'ফুলকপির মতো শীতকালীন ফসল। শীতকালে সব বিভাগে চাষ হয়।',
 'https://hub.suttons.co.uk/wp-content/uploads/2025/01/suttons.cabbage.sunta_.jpg'),

('Brinjal',
 'বেগুন',
 NULL,
 ARRAY[2, 3, 8, 9],
 ARRAY[4, 5, 10, 11, 12],
 '20–30 ton/hectare',
 'Year-round vegetable crop. Two main seasons — summer and autumn. Narsingdi, Comilla, and Jessore are main producers.',
 'সারা বছর চাষযোগ্য সবজি। দুটি প্রধান মৌসুম — গ্রীষ্ম ও শরৎ।',
 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQm57zoB35nEu0O0duU3DwqtE2CdMuhCIov1g&s'),

('Bitter Gourd',
 'করলা',
 NULL,
 ARRAY[2, 3, 4],
 ARRAY[5, 6, 7],
 '8–12 ton/hectare',
 'Summer vegetable, heat-tolerant climbing crop. Requires trellis support. Rich in vitamins and widely consumed across Bangladesh.',
 'গ্রীষ্মকালীন সবজি, উষ্ণতা সহিষ্ণু লতানো ফসল। মাচা সহায়তা প্রয়োজন।',
 'https://kitchenarchives.com/wp-content/uploads/2017/06/2-Bitter-Gourds.jpg'),

('Okra',
 'ঢেঁড়স',
 NULL,
 ARRAY[3, 4],
 ARRAY[5, 6, 7, 8],
 '8–15 ton/hectare',
 'Summer crop that grows well in all districts of Bangladesh. Prefers warm temperature and well-drained soil.',
 'গ্রীষ্মকালীন ফসল যা বাংলাদেশের সব জেলায় ভালো জন্মে।',
 'https://www.cookedandloved.com/wp-content/uploads/2020/02/what-is-okra-s.jpg'),

('Pumpkin',
 'কুমড়া',
 NULL,
 ARRAY[1, 2, 3],
 ARRAY[4, 5, 6],
 '15–25 ton/hectare',
 'Spring-summer crop needing open space. Both red and white varieties grown. Rich in vitamins A and C.',
 'বসন্ত-গ্রীষ্মকালীন ফসল, খোলা জায়গা প্রয়োজন। লাল ও সাদা উভয় জাত চাষ হয়।',
 'https://i0.wp.com/post.medicalnewstoday.com/wp-content/uploads/sites/3/2019/11/a-bunch-of-pumpkins-in-a-box.jpg?w=1155&h=1734'),

('Ridge Gourd',
 'ঝিঙে',
 NULL,
 ARRAY[3, 4],
 ARRAY[5, 6, 7, 8],
 '10–15 ton/hectare',
 'Summer climbing vegetable. Needs warm temperature and trellis. Widely grown in Dhaka, Mymensingh, and Sylhet divisions.',
 'গ্রীষ্মকালীন লতানো সবজি। উষ্ণ তাপমাত্রা ও মাচা প্রয়োজন।',
 'https://5.imimg.com/data5/DT/ET/YV/SELLER-63277527/ridged-gourd-500x500.jpg'),

('Bottle Gourd',
 'লাউ',
 NULL,
 ARRAY[9, 10, 11],
 ARRAY[12, 1, 2, 3],
 '20–30 ton/hectare',
 'Cool and warm season climbing vegetable. Winter planting gives highest yield. Grown across all divisions of Bangladesh.',
 'শীতল ও উষ্ণ মৌসুমের লতানো সবজি। শীতকালীন রোপণে সর্বোচ্চ ফলন।',
 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQq_PL0XSSmQsKqG2O0hA_IDVJAZK-TiVJXGA&s'),

('Spinach',
 'পালং শাক',
 NULL,
 ARRAY[10, 11, 12],
 ARRAY[12, 1, 2],
 '10–15 ton/hectare',
 'Cool season leafy vegetable. Fast growing, ready in 30 to 40 days. High in iron and vitamins. Grown in all winter districts.',
 'শীতল মৌসুমের পাতাজাতীয় সবজি। দ্রুত বর্ধনশীল, ৩০–৪০ দিনে প্রস্তুত।',
 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTaD6rbm25Wnv4RiqSuc2yznskg2g_4CXvcaA&s'),

('Red Amaranth',
 'লাল শাক',
 NULL,
 ARRAY[3, 4, 9, 10],
 ARRAY[4, 5, 10, 11],
 '8–12 ton/hectare',
 'Fast-growing leafy vegetable grown in summer and autumn. Popular in rural households. Rich in iron and calcium.',
 'গ্রীষ্ম ও শরৎ মৌসুমে চাষ হওয়া দ্রুত বর্ধনশীল শাকসবজি।',
 'https://specialtyproduce.com/sppics/5382.png'),

-- ── SPICES ──────────────────────────────────────────────────

('Garlic',
 'রসুন',
 NULL,
 ARRAY[10, 11],
 ARRAY[2, 3, 4],
 '5–8 ton/hectare',
 'Winter spice crop. Faridpur, Rajshahi, and Magura are main producing districts. Requires well-drained sandy loam soil.',
 'শীতকালীন মসলা ফসল। ফরিদপুর, রাজশাহী ও মাগুরা প্রধান উৎপাদনকারী জেলা।',
 'https://islandhealth.org/wp-content/uploads/2025/03/blog-size-graphics-1024x683.jpg'),

('Onion',
 'পেঁয়াজ',
 NULL,
 ARRAY[10, 11, 12],
 ARRAY[2, 3, 4],
 '8–15 ton/hectare',
 'Important winter spice crop. Pabna, Faridpur, and Rajshahi are major growing areas. High demand throughout the year.',
 'গুরুত্বপূর্ণ শীতকালীন মসলা ফসল। পাবনা, ফরিদপুর ও রাজশাহী প্রধান এলাকা।',
 'https://cdn.wikifarmer.com/images/detailed/2023/10/iStock-825545458.jpg'),

('Turmeric',
 'হলুদ',
 NULL,
 ARRAY[3, 4, 5],
 ARRAY[12, 1, 2],
 '20–30 ton/hectare (fresh rhizome)',
 'Long-season spice crop taking 8 to 10 months. Comilla, Sylhet, and Mymensingh are major producing areas.',
 'দীর্ঘমেয়াদী মসলা ফসল, ৮–১০ মাস লাগে। কুমিল্লা, সিলেট ও ময়মনসিংহ প্রধান এলাকা।',
 'https://www.gardenia.net/wp-content/uploads/2025/05/ChatGPT-Image-May-30-2025-10_22_28-AM.jpg'),

('Ginger',
 'আদা',
 NULL,
 ARRAY[3, 4, 5],
 ARRAY[11, 12, 1],
 '15–25 ton/hectare (fresh rhizome)',
 'Long-duration spice crop. Sylhet, Rangamati, and Chittagong Hill Tracts are main producing areas. Prefers partial shade.',
 'দীর্ঘমেয়াদী মসলা ফসল। সিলেট, রাঙামাটি ও পার্বত্য চট্টগ্রাম প্রধান এলাকা।',
 'https://www.health.com/thmb/Cx6c3TOE3IZgAudWvVzzIEbT5mM=/6240x0/filters:no_upscale():max_bytes(150000):strip_icc()/Health-GettyImages-2191967186-809246d0fff546049f1e997f1764d0ec.jpg'),

('Chili',
 'মরিচ',
 NULL,
 ARRAY[10, 11],
 ARRAY[1, 2, 3, 4],
 '3–5 ton/hectare (dry)',
 'Winter spice crop widely grown across Bangladesh. Bogra, Joypurhat, and Rajshahi are major districts. Both fresh and dried chili in demand.',
 'শীতকালীন মসলা ফসল। বগুড়া, জয়পুরহাট ও রাজশাহী প্রধান জেলা।',
 ''),

('Coriander',
 'ধনিয়া',
 NULL,
 ARRAY[10, 11],
 ARRAY[1, 2],
 '1–2 ton/hectare (dry seed)',
 'Cool season herb and spice. Both leaves and seeds used in cooking. Widely grown in winter across all divisions.',
 'শীতল মৌসুমের ভেষজ ও মসলা। পাতা ও বীজ উভয়ই রান্নায় ব্যবহৃত হয়।',
 'https://www.tastingtable.com/img/gallery/best-spicy-chile-peppers-hottest-pepper-how-to-cook-with-chiles/l-intro-1670518347.jpg'),

-- ── FRUITS ──────────────────────────────────────────────────

('Mango',
 'আম',
 NULL,
 ARRAY[1, 2],
 ARRAY[5, 6, 7],
 '8–15 ton/hectare',
 'King of fruits in Bangladesh. Rajshahi and Chapainawabganj are famous for Fazli, Langra, and Himsagar varieties. Flowers in January–February.',
 'বাংলাদেশে ফলের রাজা। ফজলি, ল্যাংড়া ও হিমসাগর জাতের জন্য রাজশাহী ও চাঁপাই নবাবগঞ্জ বিখ্যাত।',
 'https://snaped.fns.usda.gov/sites/default/files/styles/crop_ratio_7_5/public/seasonal-produce/2018-05/mango.jpg.webp?itok=OYWyI1lN'),

('Banana',
 'কলা',
 NULL,
 ARRAY[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
 ARRAY[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
 '20–35 ton/hectare',
 'Year-round fruit crop. Mymensingh, Narsingdi, and Rangpur are largest producing districts. Sabri and Amrit Sagar are popular varieties.',
 'সারা বছর পাওয়া যায়। ময়মনসিংহ, নরসিংদী ও রংপুর প্রধান উৎপাদনকারী জেলা।',
 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTVPq9agX9xfIskW55jvtpxNOqwyaR0Y8ZFww&s'),

('Jackfruit',
 'কাঁঠাল',
 NULL,
 ARRAY[1, 2],
 ARRAY[5, 6, 7, 8],
 '10–20 ton/hectare',
 'National fruit of Bangladesh. Large tropical tree fruit. Dhaka, Mymensingh, and Gazipur are main production areas. Peak season June to July.',
 'বাংলাদেশের জাতীয় ফল। ঢাকা, ময়মনসিংহ ও গাজীপুর প্রধান উৎপাদন এলাকা।',
 'https://assets.clevelandclinic.org/transform/83980869-7c2c-4978-9458-91168f785166/eatJackfruit-823672534-770x533-1_jpg'),

('Lychee',
 'লিচু',
 NULL,
 ARRAY[12, 1],
 ARRAY[5, 6],
 '5–10 ton/hectare',
 'Early summer delicacy. Rajshahi, Dinajpur, and Rangpur are famous for lychee. Fruit matures in May to June. High market demand.',
 'গ্রীষ্মের শুরুতে পাওয়া যায়। রাজশাহী, দিনাজপুর ও রংপুর লিচুর জন্য বিখ্যাত।',
 'https://www.popsci.com/wp-content/uploads/2022/01/05/lychee-scaled.jpg?quality=85&w=2048'),

('Guava',
 'পেয়ারা',
 NULL,
 ARRAY[2, 3],
 ARRAY[7, 8, 9, 10],
 '15–25 ton/hectare',
 'Barisal and Pirojpur famous for Swarupkathi guava. Harvested in monsoon and post-monsoon. Rich in vitamin C.',
 'স্বরূপকাঠির পেয়ারার জন্য বরিশাল ও পিরোজপুর বিখ্যাত। বর্ষা ও বর্ষা-পরবর্তীতে কাটা হয়।',
 'https://www.health.com/thmb/XlWTD8TZF5574DVtMEfD-XSj5Lg=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc()/Guava-15d1050d22034909bfca038ef1f8aaa2.jpg'),

('Watermelon',
 'তরমুজ',
 NULL,
 ARRAY[1, 2],
 ARRAY[3, 4, 5],
 '20–35 ton/hectare',
 'Summer fruit. Char areas of Bhola, Noakhali, and Barisal are main production zones. High water content, popular in summer.',
 'গ্রীষ্মকালীন ফল। ভোলা, নোয়াখালী ও বরিশালের চর অঞ্চল প্রধান উৎপাদন এলাকা।',
 ''),

('Papaya',
 'পেঁপে',
 NULL,
 ARRAY[3, 4, 9, 10],
 ARRAY[7, 8, 9, 1, 2],
 '30–50 ton/hectare',
 'Year-round fruiting crop after initial establishment. Tangail, Gazipur, and Mymensingh are major producing areas.',
 'প্রতিষ্ঠার পর সারা বছর ফল দেয়। টাঙ্গাইল, গাজীপুর ও ময়মনসিংহ প্রধান উৎপাদন এলাকা।',
 'https://snaped.fns.usda.gov/sites/default/files/styles/crop_ratio_7_5/public/seasonal-produce/2018-05/watermelon.jpg.webp?itok=4TjwcpU9'),

('Pineapple',
 'আনারস',
 NULL,
 ARRAY[5, 6],
 ARRAY[5, 6, 7, 8],
 '15–25 ton/hectare',
 'Tropical fruit grown mainly in Sylhet, Tangail, and Chittagong Hill Tracts. Jaldhup and Honey Queen are popular varieties.',
 'গ্রীষ্মমণ্ডলীয় ফল, প্রধানত সিলেট, টাঙ্গাইল ও পার্বত্য চট্টগ্রামে চাষ হয়।',
 'https://upload.wikimedia.org/wikipedia/commons/7/74/%E0%B4%95%E0%B5%88%E0%B4%A4%E0%B4%9A%E0%B5%8D%E0%B4%9A%E0%B4%95%E0%B5%8D%E0%B4%95.jpg'),

('Coconut',
 'নারিকেল',
 NULL,
 ARRAY[6, 7],
 ARRAY[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
 '80–120 nuts/tree/year',
 'Perennial tree crop available year-round. Coastal areas of Barisal, Patuakhali, and Khulna are major producers.',
 'বহুবর্ষজীবী বৃক্ষ ফসল, সারা বছর পাওয়া যায়। বরিশাল, পটুয়াখালী ও খুলনার উপকূলীয় এলাকা প্রধান উৎপাদক।',
 'https://www.paperandtea.com/cdn/shop/articles/Kokosnuss_00dc9916-deb3-4cfe-8151-107fc85f6136.jpg?v=1756478271&width=1024'),

-- ── OILSEEDS ────────────────────────────────────────────────

('Mustard',
 'সরিষা',
 NULL,
 ARRAY[10, 11],
 ARRAY[1, 2],
 '1.0–1.8 ton/hectare',
 'Main oilseed crop of Bangladesh. Creates golden yellow fields in winter. Rajshahi, Jessore, and Pabna are major areas. Short duration crop of 80 to 90 days.',
 'বাংলাদেশের প্রধান তেলবীজ ফসল। শীতকালে সোনালী হলুদ মাঠ তৈরি করে। ৮০–৯০ দিনের স্বল্পমেয়াদী ফসল।',
 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRKFHkPu9t-iCD99vWb2TDAUu9uMd3BfxuypQ&s'),

('Sesame',
 'তিল',
 NULL,
 ARRAY[3, 4],
 ARRAY[6, 7],
 '0.5–1.0 ton/hectare',
 'Summer oilseed crop. Drought tolerant and suitable for light soil. Rangpur and Rajshahi are main producing divisions.',
 'গ্রীষ্মকালীন তেলবীজ ফসল। খরা সহিষ্ণু ও হালকা মাটির জন্য উপযুক্ত।',
 'https://cdn.britannica.com/66/212766-050-FF1A49A0/sesame-seeds-wooden-spoon.jpg'),

-- ── PULSES ──────────────────────────────────────────────────

('Lentil',
 'মসুর ডাল',
 NULL,
 ARRAY[10, 11],
 ARRAY[2, 3],
 '1.0–1.5 ton/hectare',
 'Most important rabi pulse crop. Rajshahi, Pabna, and Kushtia are major growing areas. Protein-rich and widely consumed.',
 'সবচেয়ে গুরুত্বপূর্ণ রবি মৌসুমের ডাল ফসল। রাজশাহী, পাবনা ও কুষ্টিয়া প্রধান এলাকা।',
 'https://www.keepingthepeas.com/wp-content/uploads/2022/11/red-lentils-in-wood-bowl.jpg'),

('Chickpea',
 'ছোলা',
 NULL,
 ARRAY[10, 11],
 ARRAY[2, 3],
 '1.0–2.0 ton/hectare',
 'Winter pulse crop. Cultivated in drier parts of Rajshahi, Bogra, and Rangpur divisions. Used in cooking and as a snack.',
 'শীতকালীন ডাল ফসল। রাজশাহী, বগুড়া ও রংপুরের শুষ্ক অঞ্চলে চাষ হয়।',
 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT5_XDg88wObYm8nxDqJY8O1O7FSI9Oruh3QQ&s'),

('Black Gram',
 'কালাই ডাল',
 NULL,
 ARRAY[7, 8],
 ARRAY[10, 11],
 '0.8–1.2 ton/hectare',
 'Kharif pulse crop. Grown after aman paddy or as intercrop. Rajshahi and Chapainawabganj are major areas.',
 'খরিফ মৌসুমের ডাল ফসল। আমন ধানের পরে বা মিশ্র ফসল হিসেবে চাষ হয়।',
 'https://aarogyamastu.in/wp-content/uploads/2022/06/black-gram.jpg'),

('Mung Bean',
 'মুগ ডাল',
 NULL,
 ARRAY[2, 3],
 ARRAY[5, 6],
 '0.8–1.5 ton/hectare',
 'Short duration summer pulse crop. Grown after rabi crops. Faridpur, Barisal, and coastal areas are main production zones.',
 'স্বল্পমেয়াদী গ্রীষ্মকালীন ডাল ফসল। রবি ফসলের পর চাষ হয়।',
 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ5Y9ZX5x2qY5n-4AZxwn71v-viR2ZwR9M3Vw&s'),

('Groundnut',
 'চিনাবাদাম',
 NULL,
 ARRAY[3, 4],
 ARRAY[7, 8],
 '1.5–2.5 ton/hectare',
 'Summer oilseed and pulse crop. Grown in sandy loam soils of Dinajpur, Rangpur, and char areas. High oil content.',
 'গ্রীষ্মকালীন তেলবীজ ও ডাল ফসল। দিনাজপুর, রংপুর ও চরাঞ্চলের বেলে দোআঁশ মাটিতে চাষ হয়।',
 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQX4-OuVBESIfeRVCsFnLstkRLvDRAUpeSlGA&s');